// Licensed to OpenForge under one or more agreements.
// OpenForge licenses this file to you under the GNU General Public License v3.0 license.
// See the LICENSE file in the project root for more information.

namespace OpenForge.Server.Enumerations
{
    public enum MatchmakingMessageType : byte
    {
        CNetAcceptRegisterGroupForPvPAutomatchFunDuelAction = 0x26,
        CNetAcceptRegisterGroupForPvPAutomatchFunDuelNotification = 0x25,
        CNetAssignedLootFinishedNotification = 0x36,
        CNetAssignLootRewardItemToCharacterRMC = 0x48,
        CNetAssignLootRewardItemToCharacterRMR = 0x5E,
        CNetCancelCustomGameRMC = 0x41,
        CNetCancelCustomGameRMR = 0x57,
        CNetCancelGroupPvPAutomatchRMC = 0x3C,
        CNetCancelGroupPvPAutomatchRMR = 0x52,
        CNetCancelRegisterCharacterForPvPAutomatchFunDuelRMC = 0x45,
        CNetCancelRegisterCharacterForPvPAutomatchFunDuelRMR = 0x5B,
        CNetCancelWaitForMatchAction = 0xD,
        CNetChangeCustomGameOpenForOtherPlayersStateRMC = 0x40,
        CNetChangeCustomGameOpenForOtherPlayersStateRMR = 0x56,
        CNetChangeCustomGameSlotRMC = 0x3B,
        CNetChangeCustomGameSlotRMR = 0x51,
        CNetCharacterForMatchCompleteNotification = 0xC,
        CNetCharacterGetsRewardCardNotification = 0x9,
        CNetCharacterJoinedFunDuelNotification = 0x33,
        CNetCharacterJoinedGroupNotification = 0x27,
        CNetCharacterLeavesGroupNotification = 0x29,
        CNetConvertUpgradeToTokensRMC = 0x1,
        CNetConvertUpgradeToTokensRMR = 0x4D,
        CNetCreateCustomGameRMC = 0x43,
        CNetCreateCustomGameRMR = 0x59,
        CNetCreateGameChannelSMR = 0x2,
        CNetCreateGroupSMR = 0x4A,
        CNetCurrentParticipateTournamentNotification = 0x19,
        CNetCustomGameCreatedNotification = 0x2A,
        CNetCustomGameDestroyedNotification = 0x2F,
        CNetCustomGameUpdatedNotification = 0x2C,
        CNetDeclineRegisterGroupForPvPAutomatchFunDuelAction = 0x24,
        CNetEliminationGameStatiListUpdatedNotification = 0x10,
        CNetEliminationPlayerListUpdatedNotification = 0x12,
        CNetEliminationWinnerNotification = 0xE,
        CNetGetAllCriteriasRMC = 0x8,
        CNetGetAllCriteriasRMR = 0x4E,
        CNetGetAllCurrentTournamentsRMC = 0x6,
        CNetGetAllCurrentTournamentsRMR = 0x4F,
        CNetGetAllOpenCustomGamesRMC = 0x3F,
        CNetGetAllOpenCustomGamesRMR = 0x55,
        CNetGetAllUpcommingTournamentsRMC = 0x7,
        CNetGetAllUpcommingTournamentsRMR = 0x50,
        CNetGetFinishedMapsForCharacterRMC = 0x42,
        CNetGetFinishedMapsForCharacterRMR = 0x58,
        CNetGroupLeaderLeavesGroupNotification = 0x28,
        CNetGroupMatchmakingAbortedForAutomatchBecausePlayerDisconnectsNotification = 0x22,
        CNetJoinOpenCustomGameRMC = 0x3E,
        CNetJoinOpenCustomGameRMR = 0x54,
        CNetLeaderAssignedLootSessionStartedNotification = 0x39,
        CNetLeaveCharacterForFunDuelAction = 0x20,
        CNetLeaveCharacterForFunDuelNotification = 0x1F,
        CNetLeaveCustomGameAction = 0x30,
        CNetLeaveEliminationAction = 0x13,
        CNetLeaveTournamentAction = 0x15,
        CNetMatchFinishedNotification = 0x2E,
        CNetMatchLostAction = 0xB,
        CNetMatchStartedForUnteamedPlayersNotification = 0x2D,
        CNetMatchWinAction = 0xA,
        CNetMergeGroupSMR = 0x3,
        CNetNeedorGreedSessionFinishedNotification = 0x37,
        CNetNeedorGreedSessionStartedNotification = 0x38,
        CNetNeedOrGreedVoteForRewardItemRMC = 0x49,
        CNetNeedOrGreedVoteForRewardItemRMR = 0x5F,
        CNetNextEliminationRoundStartsInTimeNotification = 0x4,
        CNetNextTournamentRoundStartsInTimeNotification = 0x5,
        CNetNotEnoughtPlayersForTournamentNotification = 0x18,
        CNetPlayerDeclineRegisterGroupForAutomatchNotification = 0x23,
        CNetPlayerReadyStatusChangedNotification = 0x32,
        CNetPlayerReadyStatusChangedRMC = 0x47,
        CNetPlayerReadyStatusChangedRMR = 0x5D,
        CNetRegisterCharacterForAutomatchRankedDuelAction = 0x21,
        CNetRegisterCharacterForCompetitionAction = 0x1E,
        CNetRegisterCharacterForDuelAction = 0x34,
        CNetRegisterCharacterForEliminationAction = 0x1D,
        CNetRegisterCharacterForFunDuelAction = 0x31,
        CNetRegisterCharacterForGameAction = 0x35,
        CNetRegisterCharacterForPvPAutomatchFunDuelRMC = 0x46,
        CNetRegisterCharacterForPvPAutomatchFunDuelRMR = 0x5C,
        CNetRegisterCharacterForTournamentAction = 0x1B,
        CNetRegisterGameSMR = 0x4B,
        CNetRegisterGroupForPvPAutomatchFunDuelNotification = 0x2B,
        CNetRegisterGroupForPvPAutomatchFunDuelRMC = 0x44,
        CNetRegisterGroupForPvPAutomatchFunDuelRMR = 0x5A,
        CNetReJoinTournamentAction = 0x1C,
        CNetSetSpeedrunRMC = 0x3A,
        CNetSetSpeedrunRMR = 0x4C,
        CNetStartCustomGameRMC = 0x3D,
        CNetStartCustomGameRMR = 0x53,
        CNetToLateLoginForTournamentNotification = 0x16,
        CNetTournamentFinishedNotification = 0x14,
        CNetTournamentGameStatiListUpdatedNotification = 0xF,
        CNetTournamentMatchInstantWinNotification = 0x17,
        CNetTournamentParticipantListUpdatedNotification = 0x11,
        CNetTournamentStartsNotification = 0x1A,
    }
}
