// Licensed to OpenForge under one or more agreements.
// OpenForge licenses this file to you under the GNU General Public License v3.0 license.
// See the LICENSE file in the project root for more information.

namespace OpenForge.Server.Enumerations
{
    public enum PreGameMessageType : byte
    {
        CNetActivateScratchCardForCharacterRMC = 0x1F,
        CNetActivateScratchCardForCharacterRMR = 0x47,
        CNetAddMissingDecksWhenUpgradeFromTrialToFullVersionSMC = 0x1,
        CNetAddMissingDecksWhenUpgradeFromTrialToFullVersionSMR = 0x34,
        CNetBuyUpgradeRMC = 0x22,
        CNetBuyUpgradeRMR = 0x4A,
        CNetCombineCardUpgradesRMC = 0x23,
        CNetCombineCardUpgradesRMR = 0x4B,
        CNetCreateCharacterRMC = 0x17,
        CNetCreateCharacterRMR = 0x40,
        CNetCreateNewLimitedPoolRMC = 0x10,
        CNetCreateNewLimitedPoolRMR = 0x38,
        CNetDeleteCharacterRMC = 0x16,
        CNetDeleteCharacterRMR = 0x3F,
        CNetDeleteDeckForCharacterRMC = 0x19,
        CNetDeleteDeckForCharacterRMR = 0x3E,
        CNetDeleteIngameMailRMC = 0x11,
        CNetDeleteIngameMailRMR = 0x39,
        CNetDisbandLimitedPoolRMC = 0xE,
        CNetDisbandLimitedPoolRMR = 0x36,
        CNetDoesServerKnowUsergeneratedMapRMC = 0xA,
        CNetDoesServerKnowUsergeneratedMapRMR = 0x2E,
        CNetDownloadUserGeneratedMapFileChunkRMC = 0x6,
        CNetDownloadUserGeneratedMapFileChunkRMR = 0x2A,
        CNetGetAllActiveBoostItemsByCharacterRMC = 0xD,
        CNetGetAllActiveBoostItemsByCharacterRMR = 0x33,
        CNetGetAllBoostersForCharacterRMC = 0x21,
        CNetGetAllBoostersForCharacterRMR = 0x49,
        CNetGetAllCardsForCharacterCompressedRMC = 0x26,
        CNetGetAllCardsForCharacterCompressedRMR = 0x4E,
        CNetGetAllCardsForCharacterRMC = 0x27,
        CNetGetAllCardsForCharacterRMR = 0x4F,
        CNetGetAllCardUpgradesForCharacterCompressedRMC = 0x24,
        CNetGetAllCardUpgradesForCharacterCompressedRMR = 0x4C,
        CNetGetAllCardUpgradesForCharacterRMC = 0x25,
        CNetGetAllCardUpgradesForCharacterRMR = 0x4D,
        CNetGetAllDecksForCharacterRMC = 0x1C,
        CNetGetAllDecksForCharacterRMR = 0x43,
        CNetGetAlllLimitedPoolsForCharacterRMC = 0xF,
        CNetGetAlllLimitedPoolsForCharacterRMR = 0x37,
        CNetGetAllRegisteredTournamentsForCharacterRMC = 0x1B,
        CNetGetAllRegisteredTournamentsForCharacterRMR = 0x44,
        CNetGetCharacterStatisticRMC = 0x1E,
        CNetGetCharacterStatisticRMR = 0x46,
        CNetGetIngameMailRMC = 0x14,
        CNetGetIngameMailRMR = 0x3C,
        CNetGetPlayerCredentialsPregameSMR = 0x30,
        CNetGetRankingsRMC = 0x1D,
        CNetGetRankingsRMR = 0x45,
        CNetGetStoryBookCategoryRMC = 0x13,
        CNetGetStoryBookCategoryRMR = 0x3B,
        CNetGetUserGeneratedMapsAvailableForDownloadRMC = 0x4,
        CNetGetUserGeneratedMapsAvailableForDownloadRMR = 0x28,
        CNetIsCharacterIgnoredBySMR = 0x31,
        CNetIsEligibleForFreeTomeRMC = 0xB,
        CNetIsEligibleForFreeTomeRMR = 0x2F,
        CNetIsEligibleForFullAccountRMC = 0xC,
        CNetIsEligibleForFullAccountRMR = 0x32,
        CNetOpenBoosterForCharacterRMC = 0x20,
        CNetOpenBoosterForCharacterRMR = 0x48,
        CNetOpenIngameMailRMC = 0x12,
        CNetOpenIngameMailRMR = 0x3A,
        CNetRegisterDeckForTournamentAction = 0x3,
        CNetRegisterUserGeneratedMapDownloadRMC = 0x7,
        CNetRegisterUserGeneratedMapDownloadRMR = 0x2B,
        CNetRegisterUserGeneratedMapUploadRMC = 0x9,
        CNetRegisterUserGeneratedMapUploadRMR = 0x2D,
        CNetRenameDeckForCharacterRMC = 0x18,
        CNetRenameDeckForCharacterRMR = 0x42,
        CNetSaveDeckForCharacterRMC = 0x1A,
        CNetSaveDeckForCharacterRMR = 0x41,
        CNetSendIngameMailRMC = 0x15,
        CNetSendIngameMailRMR = 0x3D,
        CNetSendUserGeneratedMapFileChunkRMC = 0x8,
        CNetSendUserGeneratedMapFileChunkRMR = 0x2C,
        CNetSetAvatarRMC = 0x5,
        CNetSetAvatarRMR = 0x29,
        CNetWaitForBoosterLockSMC = 0x2,
        CNetWaitForBoosterLockSMR = 0x35,
    }
}
